package project.AdvanceWars.enumValues;

	public enum ListeUnites {
		INFANTERIE, BAZOOKA, TANK, TANKM, VTB, DCA, ARTILLERIE, LMISS, AAIR, RECON, HELICO, HELICOTRANSPORT, CHASSEUR, BOMBARDIER, BARGE, CROISEUR, SOUSMARIN, DESTROYER;
	}
