package project.AdvanceWars.enumValues;

public enum ListeArmes {
	MITRAILLEUSE, MITRAILLEUSEAAIR, BAZOOKA, CANON, CANONDISTANCE, CANONMER, MINIGUN, MISSILES, MISSILESMER, BOMBES, ROQUETTES, TORPILLES; 
};
